### ISSUE TITLE
Implement token transfer functionality 

### ISSUE THREAD

**Issue by abhishekpatil4** [abhishekpatil4/cbdc-using-geth#1]
Use ERC20's inbuilt transfer function to transfer tokens from one account to another. Create a js function that can be invoked to transfer tokens in the app.js file.

References: 
* https://ethereum.org/en/developers/docs/standards/tokens/erc-20/

* https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/#:~:text=address%20(%20account%20).-,This%20function%20is%20a%20getter%20and%20does,the%20state%20of%20the%20contract.&text=The%20ERC%2D20%20standard%20allows,spend%20on%20behalf%20of%20owner%20.

**Comment by WaniAthar** [comment]
> Use ERC20's inbuilt transfer function to transfer tokens from one account to another. Create a js function that can be invoked to transfer tokens in the app.js file.
> 
> References: 
> * https://ethereum.org/en/developers/docs/standards/tokens/erc-20/
> 
> * https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/#:~:text=address%20(%20account%20).-,This%20function%20is%20a%20getter%20and%20does,the%20state%20of%20the%20contract.&text=The%20ERC%2D20%20standard%20allows,spend%20on%20behalf%20of%20owner%20.
> 
> 

/assign
